package com.priceiq.bot;

public enum SellerState {
    START,
    AWAITING_CONTACT,
    MAIN_MENU,
    AWAITING_SUPPORT_MESSAGE,
    AWAITING_OPERATOR_REPLY,
    ADD_PRODUCT_PHOTO,
    ADD_PRODUCT_NAME,
    ADD_PRODUCT_PRICE,
    ADD_PRODUCT_DESCRIPTION,
    ADD_PRODUCT_CONFIRM,
    UPDATE_PRICE_SELECT,
    UPDATE_PRICE_ENTER
}
